//api actions
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_API_ERROR = 'SET_API_ERROR';
export const SET_AXIOS_HEADER = 'SET_AXIOS_HEADER';
export const SET_MINION_DATA = 'SET_MINION_DATA';
export const INCREMENT_API_COUNT = 'INCREMENT_API_COUNT';
export const STORE_UNAVAILABLE_MINIONS = 'STORE_UNAVAILABLE_MINIONS';

//calculator actions
export const INIT_CALCULATOR = 'INIT_CALCULATOR';
export const SET_TIER = 'SET_TIER';
export const RESET_TIER = 'RESET_TIER';
export const CLICK_MINION = 'CLICK_MINION';
export const CLICK_TYPE = 'CLICK_TYPE';
export const CONFIRM_TYPES = 'CONFIRM_TYPES';
export const CONFIRM_MINIONS = 'CONFIRM_MINIONS';